export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_ERROR = 'FETCH_QUIZES_ERROR';
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const QUIZ_FINISH  = 'QUIZ_FINISH';
export const QUIZ_NEXT_QUESTION = 'QUIZ_NEXT_QUESTION';
export const QUIZ_RETRY_CLICK = 'QUIZ_RETRY_CLICK';

export const QUIZCREATE_SUBMIT_QUIZ_SUCCESS = 'QUIZCREATE_SUBMIT_QUIZ_SUCCESS';
export const QUIZCREATE_SUBMIT_QUIZ_ERROR = 'QUIZCREATE_SUBMIT_QUIZ_ERROR';
export const QUIZCREATE_ADD_QUESTION_CLICK = 'QUIZCREATE_ADD_QUESTION_CLICK';
export const QUIZCREATE_CHANGE_INPUT = 'QUIZCREATE_CHANGE_INPUT';
export const QUIZCREATE_CHANGE_SELECT = 'QUIZCREATE_CHANGE_SELECT';

export const AUTH_LOGIN_CLICK = 'AUTH_LOGIN_CLICK';
export const AUTH_CHANGE_INPUT = 'AUTH_CHANGE_INPUT';